const translations = {
  en: {
    "nav.product":"Product","nav.how":"How it works","nav.desktop":"Desktop","nav.mobile":"Mobile","nav.faq":"FAQ","nav.cta":"See FORYMO",
    "hero.eyebrow":"FOCUS · RHYTHM · MOMENTS","hero.title":"Your day is more than a list of tasks.","hero.lead":"FORYMO brings together what deserves your attention, what builds your daily rhythm and what needs to happen at the right moment.","hero.primary":"Explore FORYMO","hero.secondary":"See how it works","hero.trust1h":"FOCUS","hero.trust1b":"What deserves your attention","hero.trust2h":"RHYTHM","hero.trust2b":"What repeats and builds your flow","hero.trust3h":"MOMENTS","hero.trust3b":"What needs to happen at the right time",
    "mock.today":"Today","mock.tasks":"Tasks","mock.routines":"Routines","mock.reminders":"Reminders","mock.date":"Wednesday","mock.heading":"Your day, at a glance.","mock.synced":"Ready","mock.stat1":"Tasks","mock.stat2":"Routines","mock.stat3":"Reminders","mock.done":"done","mock.today2":"today","mock.focus":"Focus next","mock.task1":"Review today’s priorities","mock.task2":"Prepare tomorrow’s plan","mock.task3":"Back up your workspace","mock.complete":"Complete","mock.upcoming":"Upcoming","mock.reminder":"Reminder",
    "product.kicker":"More than task management","product.title":"FOCUS · RHYTHM · MOMENTS","product.lead":"FORYMO is not another task manager. It organizes your day around three layers: what deserves attention, what repeats and builds your rhythm, and what must happen at the right moment.",
    "features.today.title":"MOMENTS — Today","features.today.body":"Today brings the right tasks, routines and reminders into one view so you can see what matters now.","features.tasks.title":"FOCUS — Tasks","features.tasks.body":"Tasks turn attention into action by keeping what deserves your focus clear and visible.","features.routines.title":"RHYTHM — Routines","features.routines.body":"Routines give structure to what repeats, helping consistent actions become part of your everyday flow.","features.reminders.title":"MOMENTS — Reminders","features.reminders.body":"Reminders connect an action to the moment when it needs your attention.","features.backup.title":"Backup & recovery","features.backup.body":"Create verified backups and recover confidently when you need to restore your workspace.","features.control.title":"One system, under your control","features.control.body":"Focus, Rhythm and Moments work together in one understandable workspace without changing the way your real data stays under your control.",
    "how.kicker":"How FORYMO works","how.title":"From attention to rhythm to the right moment.","how.lead":"FORYMO connects what you need to do, what you want to repeat and what must surface at the right time — without turning your day into a rigid system.","how.s1h":"Capture","how.s1b":"Add the task, routine or reminder while it is still fresh.","how.s2h":"See clearly","how.s2b":"Use Today as your working view instead of searching across disconnected lists.","how.s3h":"Act","how.s3b":"Complete what matters, update status and keep the next step visible.","how.s4h":"Protect","how.s4b":"Keep verified backups so your workspace can be recovered when needed.",
    "desktop.tag":"Main application","desktop.title":"FORYMO for Windows","desktop.body":"The full desktop workspace where Focus, Rhythm and Moments come together through Today, Tasks, Routines, Reminders and verified Backup & Recovery.","desktop.meta":"Desktop experience","desktop.cta":"Get release updates","mobile.tag":"In development","mobile.title":"FORYMO Mobile","mobile.body":"A companion experience designed to keep the essentials of your FORYMO workspace close when you are away from your PC.","mobile.meta":"Companion experience","mobile.cta":"Production release will follow testing",
    "trust.kicker":"Built for confidence","trust.title":"Your system should help you live the day, not manage the system.","trust.p1":"Focus for what deserves attention","trust.p2":"Rhythm for what builds consistency","trust.p3":"Moments for what belongs at the right time","trust.p4":"English and Greek with meaning-first localization",
    "faq.title":"Good questions. Clear answers.","faq.q1":"What is FORYMO?","faq.a1":"FORYMO is a personal productivity system built around Focus, Rhythm and Moments: Tasks support Focus, Routines build Rhythm, and Reminders with Today bring the right things into the right Moments.","faq.q2":"Is FORYMO available in Greek?","faq.a2":"Yes. FORYMO stays FORYMO in every language, while menus and explanations are localized into natural Greek based on meaning, not word-for-word machine translation.","faq.q3":"Is the mobile app available now?","faq.a3":"The mobile companion is in active development and will be released only after the required testing and acceptance steps are complete.","faq.q4":"Can I recover my data?","faq.a4":"The Windows application includes a verified Backup & Recovery workflow designed to create, verify, preview and apply approved recovery backups.",
    "cta.kicker":"FOCUS · RHYTHM · MOMENTS","cta.title":"Give your day focus, rhythm and the right moments.","cta.body":"FORYMO brings Focus, Rhythm and Moments together in one clear personal system.","cta.button":"Back to the top","footer.tagline":"Focus. Rhythm. Moments.","footer.note":"All rights reserved."
  },
  el: {
    "nav.product":"Το FORYMO","nav.how":"Πώς λειτουργεί","nav.desktop":"Windows","nav.mobile":"Mobile","nav.faq":"Συχνές ερωτήσεις","nav.cta":"Δες το FORYMO",
    "hero.eyebrow":"FOCUS · RHYTHM · MOMENTS","hero.title":"Η ημέρα σου είναι κάτι περισσότερο από μια λίστα εργασιών.","hero.lead":"Το FORYMO ενώνει όσα αξίζουν την προσοχή σου, όσα χτίζουν τον καθημερινό σου ρυθμό και όσα πρέπει να συμβούν τη σωστή στιγμή.","hero.primary":"Γνώρισε το FORYMO","hero.secondary":"Δες πώς λειτουργεί","hero.trust1h":"FOCUS","hero.trust1b":"Τι αξίζει την προσοχή σου","hero.trust2h":"RHYTHM","hero.trust2b":"Τι επαναλαμβάνεται και χτίζει τη ροή σου","hero.trust3h":"MOMENTS","hero.trust3b":"Τι πρέπει να συμβεί τη σωστή στιγμή",
    "mock.today":"Η ημέρα σου","mock.tasks":"Εργασίες","mock.routines":"Συνήθειες","mock.reminders":"Υπενθυμίσεις","mock.date":"Τετάρτη","mock.heading":"Η ημέρα σου, με μια ματιά.","mock.synced":"Έτοιμο","mock.stat1":"Εργασίες","mock.stat2":"Συνήθειες","mock.stat3":"Υπενθυμίσεις","mock.done":"ολοκληρώθηκαν","mock.today2":"σήμερα","mock.focus":"Επόμενη προτεραιότητα","mock.task1":"Έλεγξε τις σημερινές προτεραιότητες","mock.task2":"Ετοίμασε το πλάνο της αυριανής ημέρας","mock.task3":"Δημιούργησε αντίγραφο ασφαλείας","mock.complete":"Ολοκληρώθηκε","mock.upcoming":"Ακολουθεί","mock.reminder":"Υπενθύμιση",
    "product.kicker":"Περισσότερο από task management","product.title":"FOCUS · RHYTHM · MOMENTS","product.lead":"Το FORYMO δεν παρουσιάζεται ως ακόμη ένας task manager. Οργανώνει την ημέρα σου σε τρία επίπεδα: τι αξίζει την προσοχή σου, τι επαναλαμβάνεται και χτίζει τον ρυθμό σου και τι πρέπει να συμβεί τη σωστή στιγμή.",
    "features.today.title":"MOMENTS — Η ημέρα σου","features.today.body":"Η Ημέρα σου φέρνει τις σωστές εργασίες, συνήθειες και υπενθυμίσεις σε μία εικόνα, ώστε να βλέπεις τι έχει σημασία τώρα.","features.tasks.title":"FOCUS — Εργασίες","features.tasks.body":"Οι Εργασίες μετατρέπουν την προσοχή σε πράξη, κρατώντας καθαρό και ορατό ό,τι αξίζει την εστίασή σου.","features.routines.title":"RHYTHM — Συνήθειες","features.routines.body":"Οι Συνήθειες δίνουν δομή σε όσα επαναλαμβάνονται και βοηθούν τις σταθερές ενέργειες να γίνουν μέρος της καθημερινής σου ροής.","features.reminders.title":"MOMENTS — Υπενθυμίσεις","features.reminders.body":"Οι Υπενθυμίσεις συνδέουν μια ενέργεια με τη στιγμή που χρειάζεται την προσοχή σου.","features.backup.title":"Αντίγραφα ασφαλείας & επαναφορά","features.backup.body":"Δημιούργησε επαληθευμένα αντίγραφα ασφαλείας και επανάφερε τον χώρο εργασίας σου με σιγουριά όταν χρειαστεί.","features.control.title":"Ένα σύστημα, υπό τον έλεγχό σου","features.control.body":"Focus, Rhythm και Moments λειτουργούν μαζί σε έναν κατανοητό χώρο εργασίας, ενώ τα πραγματικά δεδομένα σου παραμένουν υπό τον δικό σου έλεγχο.",
    "how.kicker":"Πώς λειτουργεί το FORYMO","how.title":"Από την προσοχή, στον ρυθμό, στη σωστή στιγμή.","how.lead":"Το FORYMO συνδέει όσα πρέπει να κάνεις, όσα θέλεις να επαναλαμβάνεις και όσα πρέπει να εμφανίζονται τη σωστή στιγμή — χωρίς να μετατρέπει την ημέρα σου σε άκαμπτο σύστημα.","how.s1h":"Κατάγραψε","how.s1b":"Πρόσθεσε την εργασία, τη συνήθεια ή την υπενθύμιση όσο είναι ακόμη φρέσκια στο μυαλό σου.","how.s2h":"Δες καθαρά","how.s2b":"Χρησιμοποίησε την Ημέρα σου ως βασική οθόνη εργασίας, αντί να ψάχνεις σε ασύνδετες λίστες.","how.s3h":"Προχώρησε","how.s3b":"Ολοκλήρωσε ό,τι έχει σημασία, ενημέρωσε την κατάσταση και κράτησε ορατό το επόμενο βήμα.","how.s4h":"Προστάτεψε","how.s4b":"Διατήρησε επαληθευμένα αντίγραφα ασφαλείας ώστε να μπορείς να επαναφέρεις τον χώρο εργασίας σου όταν χρειαστεί.",
    "desktop.tag":"Κύρια εφαρμογή","desktop.title":"FORYMO για Windows","desktop.body":"Ο πλήρης χώρος εργασίας όπου Focus, Rhythm και Moments ενώνονται μέσα από την Ημέρα σου, τις Εργασίες, τις Συνήθειες, τις Υπενθυμίσεις και την επαληθευμένη δημιουργία αντιγράφων ασφαλείας και επαναφορά.","desktop.meta":"Εφαρμογή για υπολογιστή","desktop.cta":"Ενημερώσου για την έκδοση","mobile.tag":"Σε ανάπτυξη","mobile.title":"FORYMO Mobile","mobile.body":"Η συνοδευτική εμπειρία που σχεδιάζεται ώστε να έχεις κοντά σου τα βασικά του FORYMO όταν βρίσκεσαι μακριά από τον υπολογιστή σου.","mobile.meta":"Συνοδευτική εφαρμογή","mobile.cta":"Η τελική έκδοση θα ακολουθήσει μετά την ολοκλήρωση των δοκιμών",
    "trust.kicker":"Σχεδιασμένο για σιγουριά","trust.title":"Το σύστημά σου πρέπει να σε βοηθά να ζεις την ημέρα, όχι να διαχειρίζεσαι το ίδιο το σύστημα.","trust.p1":"Focus για όσα αξίζουν προσοχή","trust.p2":"Rhythm για όσα χτίζουν συνέπεια","trust.p3":"Moments για όσα ανήκουν στη σωστή στιγμή","trust.p4":"Αγγλικά και Ελληνικά με απόδοση της πραγματικής έννοιας",
    "faq.title":"Σωστές ερωτήσεις. Καθαρές απαντήσεις.","faq.q1":"Τι είναι το FORYMO;","faq.a1":"Το FORYMO είναι ένα προσωπικό σύστημα οργάνωσης βασισμένο στα Focus, Rhythm και Moments: οι Εργασίες υπηρετούν το Focus, οι Συνήθειες χτίζουν το Rhythm και οι Υπενθυμίσεις μαζί με την Ημέρα σου φέρνουν τα σωστά πράγματα στα σωστά Moments.","faq.q2":"Υπάρχει το FORYMO στα Ελληνικά;","faq.a2":"Ναι. Το όνομα FORYMO παραμένει πάντα FORYMO. Τα μενού και τα επεξηγηματικά κείμενα αποδίδονται σε φυσικά Ελληνικά με βάση το πραγματικό νόημα και όχι με μηχανική μετάφραση λέξη προς λέξη.","faq.q3":"Είναι διαθέσιμη τώρα η εφαρμογή για κινητό;","faq.a3":"Η mobile συνοδευτική εφαρμογή βρίσκεται σε ενεργή ανάπτυξη και θα κυκλοφορήσει μόνο αφού ολοκληρωθούν οι απαιτούμενες δοκιμές και η τελική αποδοχή.","faq.q4":"Μπορώ να επαναφέρω τα δεδομένα μου;","faq.a4":"Η εφαρμογή Windows περιλαμβάνει επαληθευμένη διαδικασία Backup & Recovery για δημιουργία, έλεγχο, προεπισκόπηση και εφαρμογή εγκεκριμένου αντιγράφου επαναφοράς.",
    "cta.kicker":"FOCUS · RHYTHM · MOMENTS","cta.title":"Δώσε στην ημέρα σου εστίαση, ρυθμό και τις σωστές στιγμές.","cta.body":"Το FORYMO ενώνει Focus, Rhythm και Moments σε ένα καθαρό προσωπικό σύστημα.","cta.button":"Επιστροφή στην αρχή","footer.tagline":"Focus. Rhythm. Moments.","footer.note":"Με επιφύλαξη παντός δικαιώματος."
  }
};

const buttons = document.querySelectorAll('.lang-btn');
const menuBtn = document.querySelector('.menu-btn');
const nav = document.querySelector('.nav');

function setLanguage(lang){
  const dict = translations[lang] || translations.en;
  document.documentElement.lang = lang === 'el' ? 'el' : 'en';
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if(dict[key]) el.textContent = dict[key];
  });
  buttons.forEach(btn => btn.classList.toggle('active', btn.dataset.lang === lang));
  localStorage.setItem('focivo-language', lang);
  document.title = 'FORYMO — Focus. Rhythm. Moments.';
}

buttons.forEach(btn => btn.addEventListener('click', () => setLanguage(btn.dataset.lang)));
menuBtn.addEventListener('click', () => {
  const open = nav.classList.toggle('open');
  menuBtn.setAttribute('aria-expanded', String(open));
});
nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => {
  nav.classList.remove('open');
  menuBtn.setAttribute('aria-expanded','false');
}));
setLanguage(localStorage.getItem('focivo-language') || 'en');
