const translations = {
  en: {
    "nav.product":"Product","nav.how":"How it works","nav.desktop":"Desktop","nav.mobile":"Mobile","nav.faq":"FAQ","nav.cta":"See FOCIVO",
    "hero.eyebrow":"A calmer way to run your day","hero.title":"Focus on what matters. FOCIVO keeps the rest organized.","hero.lead":"One focused workspace for tasks, routines, reminders and the things you need to get done — without the clutter.","hero.primary":"Explore FOCIVO","hero.secondary":"See how it works","hero.trust1h":"Clear","hero.trust1b":"One place, less noise","hero.trust2h":"Practical","hero.trust2b":"Built for everyday use","hero.trust3h":"Controlled","hero.trust3b":"Your data stays yours",
    "mock.today":"Today","mock.tasks":"Tasks","mock.routines":"Routines","mock.reminders":"Reminders","mock.date":"Wednesday","mock.heading":"Your day, at a glance.","mock.synced":"Ready","mock.stat1":"Tasks","mock.stat2":"Routines","mock.stat3":"Reminders","mock.done":"done","mock.today2":"today","mock.focus":"Focus next","mock.task1":"Review today’s priorities","mock.task2":"Prepare tomorrow’s plan","mock.task3":"Back up your workspace","mock.complete":"Complete","mock.upcoming":"Upcoming","mock.reminder":"Reminder",
    "product.kicker":"Everything in one place","product.title":"Simple enough for today. Structured enough for everything else.","product.lead":"FOCIVO brings the moving parts of your day together so you can see what matters, act on it and move on.",
    "features.today.title":"Your day","features.today.body":"See today’s tasks, routines and reminders in one clear view — without jumping between screens.","features.tasks.title":"Tasks that stay clear","features.tasks.body":"Capture what needs doing, keep the next action visible and move work forward without unnecessary complexity.","features.routines.title":"Routines that become consistent","features.routines.body":"Keep recurring actions visible and build consistency without turning your day into a rigid schedule.","features.reminders.title":"Reminders with purpose","features.reminders.body":"Set reminders for what truly needs your attention, when it needs it.","features.backup.title":"Backup & recovery","features.backup.body":"Create verified backups and recover confidently when you need to restore your workspace.","features.control.title":"Designed around control","features.control.body":"FOCIVO is built to keep your workflow understandable, practical and under your control.",
    "how.kicker":"How FOCIVO works","how.title":"Less friction between thinking and doing.","how.lead":"FOCIVO follows a simple rhythm: capture what matters, see the right things at the right time, then close the loop.","how.s1h":"Capture","how.s1b":"Add the task, routine or reminder while it is still fresh.","how.s2h":"See clearly","how.s2b":"Use Today as your working view instead of searching across disconnected lists.","how.s3h":"Act","how.s3b":"Complete what matters, update status and keep the next step visible.","how.s4h":"Protect","how.s4b":"Keep verified backups so your workspace can be recovered when needed.",
    "desktop.tag":"Main application","desktop.title":"FOCIVO for Windows","desktop.body":"The full desktop workspace for Today, Tasks, Routines, Reminders and verified Backup & Recovery.","desktop.meta":"Desktop experience","desktop.cta":"Get release updates","mobile.tag":"In development","mobile.title":"FOCIVO Mobile","mobile.body":"A companion experience designed to keep the essentials of your FOCIVO workspace close when you are away from your PC.","mobile.meta":"Companion experience","mobile.cta":"Production release will follow testing",
    "trust.kicker":"Built for confidence","trust.title":"Your system should help you think less about the system.","trust.p1":"Clear states and understandable controls","trust.p2":"Verified backup and recovery workflow","trust.p3":"Focused interface without decorative complexity","trust.p4":"English and Greek with meaning-first localization",
    "faq.title":"Good questions. Clear answers.","faq.q1":"What is FOCIVO?","faq.a1":"FOCIVO is a personal productivity workspace that brings your daily view, tasks, routines, reminders and recovery tools together.","faq.q2":"Is FOCIVO available in Greek?","faq.a2":"Yes. FOCIVO stays FOCIVO in every language, while menus and explanations are localized into natural Greek based on meaning, not word-for-word machine translation.","faq.q3":"Is the mobile app available now?","faq.a3":"The mobile companion is in active development and will be released only after the required testing and acceptance steps are complete.","faq.q4":"Can I recover my data?","faq.a4":"The Windows application includes a verified Backup & Recovery workflow designed to create, verify, preview and apply approved recovery backups.",
    "cta.kicker":"FOCIVO","cta.title":"A clearer day starts with a clearer system.","cta.body":"FOCIVO is being built for people who want structure without friction and focus without clutter.","cta.button":"Back to the top","footer.tagline":"Focus. Organize. Move forward.","footer.note":"All rights reserved."
  },
  el: {
    "nav.product":"Το FOCIVO","nav.how":"Πώς λειτουργεί","nav.desktop":"Windows","nav.mobile":"Mobile","nav.faq":"Συχνές ερωτήσεις","nav.cta":"Δες το FOCIVO",
    "hero.eyebrow":"Πιο καθαρή οργάνωση για κάθε ημέρα","hero.title":"Εστίασε σε όσα έχουν σημασία. Το FOCIVO κρατά τα υπόλοιπα οργανωμένα.","hero.lead":"Ένας συγκεντρωμένος χώρος για εργασίες, σταθερές συνήθειες, υπενθυμίσεις και όσα χρειάζεται πραγματικά να γίνουν — χωρίς περιττό θόρυβο.","hero.primary":"Γνώρισε το FOCIVO","hero.secondary":"Δες πώς λειτουργεί","hero.trust1h":"Καθαρό","hero.trust1b":"Όλα σε ένα μέρος","hero.trust2h":"Πρακτικό","hero.trust2b":"Για πραγματική καθημερινή χρήση","hero.trust3h":"Ελεγχόμενο","hero.trust3b":"Τα δεδομένα σου παραμένουν δικά σου",
    "mock.today":"Η ημέρα σου","mock.tasks":"Εργασίες","mock.routines":"Συνήθειες","mock.reminders":"Υπενθυμίσεις","mock.date":"Τετάρτη","mock.heading":"Η ημέρα σου, με μια ματιά.","mock.synced":"Έτοιμο","mock.stat1":"Εργασίες","mock.stat2":"Συνήθειες","mock.stat3":"Υπενθυμίσεις","mock.done":"ολοκληρώθηκαν","mock.today2":"σήμερα","mock.focus":"Επόμενη προτεραιότητα","mock.task1":"Έλεγξε τις σημερινές προτεραιότητες","mock.task2":"Ετοίμασε το πλάνο της αυριανής ημέρας","mock.task3":"Δημιούργησε αντίγραφο ασφαλείας","mock.complete":"Ολοκληρώθηκε","mock.upcoming":"Ακολουθεί","mock.reminder":"Υπενθύμιση",
    "product.kicker":"Όλα σε ένα μέρος","product.title":"Απλό για τη σημερινή ημέρα. Οργανωμένο για όλα τα υπόλοιπα.","product.lead":"Το FOCIVO συγκεντρώνει όσα κινούν την ημέρα σου, ώστε να βλέπεις τι έχει σημασία, να το ολοκληρώνεις και να συνεχίζεις.",
    "features.today.title":"Η ημέρα σου","features.today.body":"Δες σε μία καθαρή εικόνα τις σημερινές εργασίες, τις συνήθειες και τις υπενθυμίσεις σου, χωρίς να ψάχνεις σε διαφορετικές οθόνες.","features.tasks.title":"Εργασίες χωρίς μπέρδεμα","features.tasks.body":"Κατέγραψε τι πρέπει να γίνει, κράτησε ορατό το επόμενο βήμα και προχώρα χωρίς περιττή πολυπλοκότητα.","features.routines.title":"Συνήθειες με συνέπεια","features.routines.body":"Κράτησε ορατές τις επαναλαμβανόμενες ενέργειες και χτίσε συνέπεια χωρίς να μετατρέψεις την ημέρα σου σε άκαμπτο πρόγραμμα.","features.reminders.title":"Υπενθυμίσεις με λόγο ύπαρξης","features.reminders.body":"Όρισε υπενθυμίσεις μόνο για όσα χρειάζονται πραγματικά την προσοχή σου, όταν τη χρειάζονται.","features.backup.title":"Αντίγραφα ασφαλείας & επαναφορά","features.backup.body":"Δημιούργησε επαληθευμένα αντίγραφα ασφαλείας και επανάφερε τον χώρο εργασίας σου με σιγουριά όταν χρειαστεί.","features.control.title":"Σχεδιασμένο για να έχεις τον έλεγχο","features.control.body":"Το FOCIVO κρατά τη ροή εργασίας σου κατανοητή, πρακτική και υπό τον δικό σου έλεγχο.",
    "how.kicker":"Πώς λειτουργεί το FOCIVO","how.title":"Λιγότερη απόσταση ανάμεσα στη σκέψη και στην πράξη.","how.lead":"Η λογική είναι απλή: καταγράφεις ό,τι έχει σημασία, βλέπεις τα σωστά πράγματα την κατάλληλη στιγμή και ολοκληρώνεις τον κύκλο.","how.s1h":"Κατάγραψε","how.s1b":"Πρόσθεσε την εργασία, τη συνήθεια ή την υπενθύμιση όσο είναι ακόμη φρέσκια στο μυαλό σου.","how.s2h":"Δες καθαρά","how.s2b":"Χρησιμοποίησε την Ημέρα σου ως βασική οθόνη εργασίας, αντί να ψάχνεις σε ασύνδετες λίστες.","how.s3h":"Προχώρησε","how.s3b":"Ολοκλήρωσε ό,τι έχει σημασία, ενημέρωσε την κατάσταση και κράτησε ορατό το επόμενο βήμα.","how.s4h":"Προστάτεψε","how.s4b":"Διατήρησε επαληθευμένα αντίγραφα ασφαλείας ώστε να μπορείς να επαναφέρεις τον χώρο εργασίας σου όταν χρειαστεί.",
    "desktop.tag":"Κύρια εφαρμογή","desktop.title":"FOCIVO για Windows","desktop.body":"Ο πλήρης χώρος εργασίας για την Ημέρα σου, τις Εργασίες, τις Συνήθειες, τις Υπενθυμίσεις και την επαληθευμένη δημιουργία αντιγράφων ασφαλείας και επαναφορά.","desktop.meta":"Εφαρμογή για υπολογιστή","desktop.cta":"Ενημερώσου για την έκδοση","mobile.tag":"Σε ανάπτυξη","mobile.title":"FOCIVO Mobile","mobile.body":"Η συνοδευτική εμπειρία που σχεδιάζεται ώστε να έχεις κοντά σου τα βασικά του FOCIVO όταν βρίσκεσαι μακριά από τον υπολογιστή σου.","mobile.meta":"Συνοδευτική εφαρμογή","mobile.cta":"Η τελική έκδοση θα ακολουθήσει μετά την ολοκλήρωση των δοκιμών",
    "trust.kicker":"Σχεδιασμένο για σιγουριά","trust.title":"Το σύστημά σου πρέπει να σε βοηθά να σκέφτεσαι λιγότερο το ίδιο το σύστημα.","trust.p1":"Καθαρές καταστάσεις και κατανοητοί έλεγχοι","trust.p2":"Επαληθευμένη διαδικασία αντιγράφων ασφαλείας και επαναφοράς","trust.p3":"Εστιασμένο περιβάλλον χωρίς περιττή οπτική πολυπλοκότητα","trust.p4":"Αγγλικά και Ελληνικά με απόδοση της πραγματικής έννοιας",
    "faq.title":"Σωστές ερωτήσεις. Καθαρές απαντήσεις.","faq.q1":"Τι είναι το FOCIVO;","faq.a1":"Το FOCIVO είναι ένας προσωπικός χώρος οργάνωσης που ενώνει την καθημερινή σου εικόνα, τις εργασίες, τις συνήθειες, τις υπενθυμίσεις και τα εργαλεία επαναφοράς.","faq.q2":"Υπάρχει το FOCIVO στα Ελληνικά;","faq.a2":"Ναι. Το όνομα FOCIVO παραμένει πάντα FOCIVO. Τα μενού και τα επεξηγηματικά κείμενα αποδίδονται σε φυσικά Ελληνικά με βάση το πραγματικό νόημα και όχι με μηχανική μετάφραση λέξη προς λέξη.","faq.q3":"Είναι διαθέσιμη τώρα η εφαρμογή για κινητό;","faq.a3":"Η mobile συνοδευτική εφαρμογή βρίσκεται σε ενεργή ανάπτυξη και θα κυκλοφορήσει μόνο αφού ολοκληρωθούν οι απαιτούμενες δοκιμές και η τελική αποδοχή.","faq.q4":"Μπορώ να επαναφέρω τα δεδομένα μου;","faq.a4":"Η εφαρμογή Windows περιλαμβάνει επαληθευμένη διαδικασία Backup & Recovery για δημιουργία, έλεγχο, προεπισκόπηση και εφαρμογή εγκεκριμένου αντιγράφου επαναφοράς.",
    "cta.kicker":"FOCIVO","cta.title":"Μια πιο καθαρή ημέρα ξεκινά από ένα πιο καθαρό σύστημα.","cta.body":"Το FOCIVO δημιουργείται για ανθρώπους που θέλουν οργάνωση χωρίς τριβή και συγκέντρωση χωρίς περιττό θόρυβο.","cta.button":"Επιστροφή στην αρχή","footer.tagline":"Εστίαση. Οργάνωση. Πρόοδος.","footer.note":"Με επιφύλαξη παντός δικαιώματος."
  }
};

const buttons = document.querySelectorAll('.lang-btn');
const menuBtn = document.querySelector('.menu-btn');
const nav = document.querySelector('.nav');

function setLanguage(lang){
  const dict = translations[lang] || translations.en;
  document.documentElement.lang = lang === 'el' ? 'el' : 'en';
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if(dict[key]) el.textContent = dict[key];
  });
  buttons.forEach(btn => btn.classList.toggle('active', btn.dataset.lang === lang));
  localStorage.setItem('focivo-language', lang);
  document.title = lang === 'el' ? 'FOCIVO — Εστίαση. Οργάνωση. Πρόοδος.' : 'FOCIVO — Focus. Organize. Move forward.';
}

buttons.forEach(btn => btn.addEventListener('click', () => setLanguage(btn.dataset.lang)));
menuBtn.addEventListener('click', () => {
  const open = nav.classList.toggle('open');
  menuBtn.setAttribute('aria-expanded', String(open));
});
nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => {
  nav.classList.remove('open');
  menuBtn.setAttribute('aria-expanded','false');
}));
setLanguage(localStorage.getItem('focivo-language') || 'en');
